// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using testedotnet1.WebAPI.Model.App_Data;

namespace testedotnet1.WebAPI.Model.Migrations
{
    [DbContext(typeof(HorasContext))]
    [Migration("20201211222702_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("testedotnet1.WebAPI.Model.App_Data.Desenvolvedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Desenvolvedores");
                });

            modelBuilder.Entity("testedotnet1.WebAPI.Model.App_Data.Hora_trabalhada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Datafim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Datainicio")
                        .HasColumnType("datetime2");

                    b.Property<int?>("desenvolvedorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("desenvolvedorId");

                    b.ToTable("Horas_Trabalhadas");
                });

            modelBuilder.Entity("testedotnet1.WebAPI.Model.App_Data.Hora_trabalhada", b =>
                {
                    b.HasOne("testedotnet1.WebAPI.Model.App_Data.Desenvolvedor", "desenvolvedor")
                        .WithMany()
                        .HasForeignKey("desenvolvedorId");

                    b.Navigation("desenvolvedor");
                });
#pragma warning restore 612, 618
        }
    }
}
